---

is_debug : false
is_dev : false

http : 
  ip : 0.0.0.0
  port : 8080
  read_timeout : 5s
  write_timeout : 10s
  cors : 
    allowed_methods : ["GET", "POST", PATCH, DELETE]
    allowed_origins : ["http://localhost:3000"]
    allow_credentials : true
    allowed_headers : ["authorization", "content-type"]
    options_pass_through : true
    exposed_headers : []
    debug : true

app_config :
  log_level : trace
  admin_user :
    admin_email : admin
    admin_pwd : admin

# Locally:
postgresql :
  psql_username : root
  psql_password : 12345
  psql_host : localhost
  psql_port : 5435
  psql_database : hospital

# Docker: 
# postgresql :
#   psql_username : root
#   psql_password : 12345
#   psql_host : db
#   psql_port : 5432
#   psql_database : hospital

---