version: '3.8'

services:
  backend:
    container_name: backend
    image: backend:local
    ports:
      - 8080:8080
    depends_on:
      - db  

  frontend:
    container_name: client_frontend
    image: frontend:local
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  db:
    container_name: postgresql
    restart: always
    image: postgres:16.2
    volumes: 
      - /home/ivan/postgresql95/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hospital
    ports:
      - 5435:5432
